### ISSUE TITLE
Problem with the plugin

### ISSUE THREAD

**Issue by AxelKohlepp** [miyako/4d-plugin-address-book#1]
Hello,
can´t get it working. Always getting error message.
![bildschirmfoto 2016-10-11 um 19 21 15](https://cloud.githubusercontent.com/assets/22775620/19281075/ba2416b4-8fe8-11e6-9609-fe27fbba93d0.png)

**Comment by miyako** [comment]
for some unknown reason x code was building for 64 bits only (you could have used the version in the v11 folder which is 32 bits, but anyway). solved by building twice and manually merging binary for both architectures.
